language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
     - ARDUINO_IDE_VERSION="1.8.7"
     - PRETTYNAME="ESP8266 WiFi Speaker"
# Optional, will default to "$TRAVIS_BUILD_DIR/Doxyfile"
#    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile

before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/smurf0969/travis-ci-arduino/master/install.sh)

install:
      - mkdir -p $HOME/Arduino/libraries
      - git clone https://github.com/earlephilhower/ESP8266Audio $HOME/Arduino/libraries/ESP8266Audio
      - git clone https://github.com/adafruit/Adafruit-GFX-Library $HOME/Arduino/libraries/Adafruit_GFX_Library
      - git clone https://github.com/adafruit/Adafruit_SSD1306 $HOME/Arduino/libraries/Adafruit_SSD1306
      - git clone https://github.com/bblanchon/ArduinoJson $HOME/Arduino/libraries/ArduinoJson
      - git clone https://github.com/tzapu/WiFiManager $HOME/Arduino/libraries/WiFiManager
     
script:
   - build_main_platforms

# Generate and deploy documentation
after_success:
  - source <(curl -SLs  https://raw.githubusercontent.com/smurf0969/travis-ci-arduino/master/library_check.sh)
#  - source <(curl -SLs  https://raw.githubusercontent.com/smurf0969/travis-ci-arduino/skip-doxygen-warnings/doxy_gen_and_deploy.sh)
