branches:
    only:
      - master
      - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
      
os: linux
dist: trusty
language: bash
sudo: false
cache:
  directories:
    - ~/arduino_ide
  #  - ~/.arduino15/packages/
before_cache:
    - rm -rf ~/arduino_ide/hardware/esp8266com
    - rm -rf  ~/arduino_ide/hardware/espressif
git:
  depth: false
  quiet: true
env:
  global:
     - PRETTYNAME="ESP8266 WiFi Speaker""

matrix:

  include:

    - env:

      - BUILD_TYPE=build_esp8266
      - BUILDDOXYGEN=false



before_install:


install:


script:
   - $TRAVIS_BUILD_DIR/travis/common.sh

# Generate and deploy documentation
after_success:
 

notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always
